// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test_service.proto

package testservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EchoRequest struct {
	Payload              string   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoRequest) Reset()         { *m = EchoRequest{} }
func (m *EchoRequest) String() string { return proto.CompactTextString(m) }
func (*EchoRequest) ProtoMessage()    {}
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba4cad72290a3024, []int{0}
}

func (m *EchoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoRequest.Unmarshal(m, b)
}
func (m *EchoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoRequest.Marshal(b, m, deterministic)
}
func (m *EchoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoRequest.Merge(m, src)
}
func (m *EchoRequest) XXX_Size() int {
	return xxx_messageInfo_EchoRequest.Size(m)
}
func (m *EchoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EchoRequest proto.InternalMessageInfo

func (m *EchoRequest) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type EchoResponse struct {
	Payload              string   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoResponse) Reset()         { *m = EchoResponse{} }
func (m *EchoResponse) String() string { return proto.CompactTextString(m) }
func (*EchoResponse) ProtoMessage()    {}
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba4cad72290a3024, []int{1}
}

func (m *EchoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoResponse.Unmarshal(m, b)
}
func (m *EchoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoResponse.Marshal(b, m, deterministic)
}
func (m *EchoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoResponse.Merge(m, src)
}
func (m *EchoResponse) XXX_Size() int {
	return xxx_messageInfo_EchoResponse.Size(m)
}
func (m *EchoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EchoResponse proto.InternalMessageInfo

func (m *EchoResponse) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type SumRequest struct {
	Values               []int32  `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumRequest) Reset()         { *m = SumRequest{} }
func (m *SumRequest) String() string { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()    {}
func (*SumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba4cad72290a3024, []int{2}
}

func (m *SumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumRequest.Unmarshal(m, b)
}
func (m *SumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumRequest.Marshal(b, m, deterministic)
}
func (m *SumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumRequest.Merge(m, src)
}
func (m *SumRequest) XXX_Size() int {
	return xxx_messageInfo_SumRequest.Size(m)
}
func (m *SumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SumRequest proto.InternalMessageInfo

func (m *SumRequest) GetValues() []int32 {
	if m != nil {
		return m.Values
	}
	return nil
}

type SumResponse struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumResponse) Reset()         { *m = SumResponse{} }
func (m *SumResponse) String() string { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()    {}
func (*SumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba4cad72290a3024, []int{3}
}

func (m *SumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumResponse.Unmarshal(m, b)
}
func (m *SumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumResponse.Marshal(b, m, deterministic)
}
func (m *SumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumResponse.Merge(m, src)
}
func (m *SumResponse) XXX_Size() int {
	return xxx_messageInfo_SumResponse.Size(m)
}
func (m *SumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SumResponse proto.InternalMessageInfo

func (m *SumResponse) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*EchoRequest)(nil), "test_service.EchoRequest")
	proto.RegisterType((*EchoResponse)(nil), "test_service.EchoResponse")
	proto.RegisterType((*SumRequest)(nil), "test_service.SumRequest")
	proto.RegisterType((*SumResponse)(nil), "test_service.SumResponse")
}

func init() { proto.RegisterFile("test_service.proto", fileDescriptor_ba4cad72290a3024) }

var fileDescriptor_ba4cad72290a3024 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x51, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0x36, 0xcc, 0x4e, 0x7c, 0xdd, 0x29, 0x88, 0x74, 0x3d, 0x8d, 0x2a, 0x18, 0x3c, 0xb4, 0x32,
	0xaf, 0x82, 0x20, 0x7a, 0xf0, 0xda, 0x7a, 0xf2, 0x22, 0x69, 0x7d, 0xb4, 0x85, 0x66, 0xaf, 0x36,
	0xc9, 0xc0, 0xbf, 0xd4, 0x7f, 0x47, 0x96, 0x74, 0xba, 0xc1, 0xf0, 0xe2, 0xf1, 0xcb, 0xf7, 0x23,
	0xdf, 0xc7, 0x03, 0x6e, 0x50, 0x9b, 0x37, 0x8d, 0xc3, 0xba, 0xad, 0x30, 0xed, 0x07, 0x32, 0xc4,
	0x67, 0xbb, 0x6f, 0xc9, 0x15, 0x84, 0x4f, 0x55, 0x43, 0x39, 0x7e, 0x58, 0xd4, 0x86, 0x47, 0x70,
	0xd2, 0xcb, 0xcf, 0x8e, 0xe4, 0x7b, 0xc4, 0x16, 0x4c, 0x9c, 0xe6, 0x5b, 0x98, 0x08, 0x98, 0x79,
	0xa1, 0xee, 0x69, 0xa5, 0xf1, 0x0f, 0xe5, 0x25, 0x40, 0x61, 0xd5, 0x36, 0xf1, 0x1c, 0xa6, 0x6b,
	0xd9, 0x59, 0xd4, 0x11, 0x5b, 0x4c, 0x44, 0x90, 0x8f, 0x28, 0xb9, 0x80, 0xd0, 0xa9, 0xc6, 0xb8,
	0x33, 0x08, 0x1c, 0xe1, 0xc2, 0x82, 0xdc, 0x83, 0xe5, 0x17, 0x83, 0xf0, 0x05, 0xb5, 0x29, 0x7c,
	0x5b, 0x7e, 0x0f, 0xc7, 0x9b, 0x12, 0x7c, 0x9e, 0xee, 0x0d, 0xdb, 0x59, 0x10, 0xc7, 0x87, 0x28,
	0xff, 0x49, 0x72, 0xc4, 0xef, 0x60, 0x52, 0x58, 0xc5, 0xa3, 0x7d, 0xd1, 0x6f, 0xdd, 0x78, 0x7e,
	0x80, 0xf9, 0x71, 0x3f, 0x03, 0x3c, 0x92, 0x2d, 0x3b, 0xfc, 0x57, 0x09, 0xc1, 0x6e, 0xd8, 0xc3,
	0xf5, 0xab, 0xa8, 0x5b, 0xd3, 0xd8, 0x32, 0xad, 0x48, 0x65, 0x35, 0x51, 0xdd, 0x61, 0xa6, 0xe4,
	0x60, 0x5a, 0xb9, 0xca, 0x9a, 0x65, 0xb6, 0xf1, 0x8f, 0xf6, 0x72, 0xea, 0x0e, 0x77, 0xfb, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0x4c, 0x97, 0x9b, 0x89, 0xce, 0x01, 0x00, 0x00,
}
